POST http://localhost:3333/goals
Content-Type: application/json

{
   "title":"jabulani",
   "desiredWeeklyFrequency": 3
}
###
GET http://localhost:3333/pending-goals
###
POST http://localhost:3333/completions
Content-Type: application/json

{
   "goalId": "m7ykpvghsjejypqep9c44bxo"
}
###
###
GET http://localhost:3333/summary